import type { ExploreCategory, ExploreProvider } from '../types/explore';
import { EXPLORE_CATEGORY_IMAGES } from './exploreCategoryImages';

const avatar = (seed: string) => `https://i.pravatar.cc/256?u=${seed}`;

export const EXPLORE_CATEGORIES_MOCK: ExploreCategory[] = [
  {
    id: 'tutoring',
    title: 'Tutoring & Academics',
    pillLabel: 'Tutoring',
    tagline: 'Learn smarter, together on campus',
    iconName: 'school-outline',
    description:
      'Math, science, writing help, exam prep, and study partners for tough courses.',
    imageUrl: EXPLORE_CATEGORY_IMAGES.tutoring,
    accentColor: '#7C3AED',
  },
  {
    id: 'tech',
    title: 'Tech & Development',
    pillLabel: 'Tech',
    tagline: 'Build the tools students actually need',
    iconName: 'code-slash-outline',
    description:
      'Websites, apps, debugging, portfolio builds, and campus tool prototypes.',
    imageUrl: EXPLORE_CATEGORY_IMAGES.tech,
    accentColor: '#2563EB',
  },
  {
    id: 'design',
    title: 'Design & Creative',
    pillLabel: 'Design',
    tagline: 'Make every campus moment look sharp',
    iconName: 'color-palette-outline',
    description:
      'Posters, branding, UI mockups, photography, and social media assets.',
    imageUrl: EXPLORE_CATEGORY_IMAGES.design,
    accentColor: '#EA580C',
  },
  {
    id: 'career',
    title: 'Career & Professional',
    pillLabel: 'Career',
    tagline: 'Stand out before graduation day',
    iconName: 'briefcase-outline',
    description:
      'Resume reviews, interview prep, LinkedIn polish, and personal statements.',
    imageUrl: EXPLORE_CATEGORY_IMAGES.career,
    accentColor: '#059669',
  },
  {
    id: 'campus',
    title: 'Campus Life & Errands',
    pillLabel: 'Campus',
    tagline: 'Small tasks handled while you study',
    iconName: 'bicycle-outline',
    description:
      'Laundry runs, deliveries, moving help, and other on-campus logistics.',
    imageUrl: EXPLORE_CATEGORY_IMAGES.campus,
    accentColor: '#DB2777',
  },
];

export const EXPLORE_PROVIDERS_MOCK: ExploreProvider[] = [
  {
    username: 'emilyl',
    displayName: 'Emily L.',
    handle: '@emilyl',
    avatarUrl: avatar('emilyl'),
    categoryId: 'tutoring',
    skillTitle: 'Organic Chemistry Tutor',
    expertiseTags: ['ORGANIC CHEMISTRY', 'BIOCHEM', 'LAB REPORTS'],
    serviceIds: ['tutoring-1', 'tutoring-3'],
    averageRating: 4.8,
    reviewCount: 73,
  },
  {
    username: 'zoem',
    displayName: 'Zoe M.',
    handle: '@zoem',
    avatarUrl: avatar('zoem'),
    categoryId: 'design',
    skillTitle: 'Social Media Creator',
    expertiseTags: ['INSTAGRAM', 'TIKTOK', 'CONTENT STRATEGY'],
    serviceIds: ['design-1', 'design-3'],
    averageRating: 4.9,
    reviewCount: 46,
  },
  {
    username: 'davidr',
    displayName: 'David R.',
    handle: '@davidr',
    avatarUrl: avatar('davidr'),
    categoryId: 'career',
    skillTitle: 'Career & LinkedIn Coach',
    expertiseTags: ['RESUMES', 'LINKEDIN', 'INTERVIEW PREP'],
    serviceIds: ['career-1', 'career-2'],
    averageRating: 5,
    reviewCount: 92,
  },
  {
    username: 'jamies',
    displayName: 'Jamie S.',
    handle: '@jamies',
    avatarUrl: avatar('jamies'),
    categoryId: 'campus',
    skillTitle: 'Campus Errands Helper',
    expertiseTags: ['GROCERY SHOPPING', 'DELIVERY', 'ORGANIZATION'],
    serviceIds: ['campus-1', 'campus-3'],
    averageRating: 4.7,
    reviewCount: 54,
  },
  {
    username: 'morganh',
    displayName: 'Morgan H.',
    handle: '@morganh',
    avatarUrl: avatar('morganh'),
    categoryId: 'tech',
    skillTitle: 'Full-Stack Developer',
    expertiseTags: ['REACT', 'NEXT.JS', 'NODE.JS', 'FIREBASE'],
    serviceIds: ['tech-1', 'tech-2'],
    averageRating: 4.9,
    reviewCount: 38,
  },
  {
    username: 'jordanp',
    displayName: 'Jordan P.',
    handle: '@jordanp',
    avatarUrl: avatar('jordanp'),
    categoryId: 'tutoring',
    skillTitle: 'Calculus & STEM Tutor',
    expertiseTags: ['CALCULUS', 'LINEAR ALGEBRA', 'EXAM PREP'],
    serviceIds: ['tutoring-1', 'tutoring-3'],
    averageRating: 4.9,
    reviewCount: 124,
  },
  {
    username: 'mialdesign',
    displayName: 'Mia L.',
    handle: '@mialdesign',
    avatarUrl: avatar('mialdesign'),
    categoryId: 'design',
    skillTitle: 'Product Designer & UX Specialist',
    expertiseTags: ['UI DESIGN', 'UX RESEARCH', 'FIGMA'],
    serviceIds: ['design-2', 'design-3'],
    averageRating: 5,
    reviewCount: 89,
  },
  {
    username: 'christdev',
    displayName: 'Chris T.',
    handle: '@christdev',
    avatarUrl: avatar('christdev'),
    categoryId: 'tech',
    skillTitle: 'Full-Stack Student Developer',
    expertiseTags: ['REACT', 'EXPO', 'DEBUGGING'],
    serviceIds: ['tech-1', 'tech-2'],
    averageRating: 4.8,
    reviewCount: 56,
  },
  {
    username: 'priyacodes',
    displayName: 'Priya N.',
    handle: '@priyacodes',
    avatarUrl: avatar('priyacodes'),
    categoryId: 'tutoring',
    skillTitle: 'Python & CS Fundamentals Coach',
    expertiseTags: ['PYTHON', 'WRITING', 'ESSAYS'],
    serviceIds: ['tutoring-1', 'tutoring-2'],
    averageRating: 4.7,
    reviewCount: 41,
  },
  {
    username: 'samruns',
    displayName: 'Sam R.',
    handle: '@samruns',
    avatarUrl: avatar('samruns'),
    categoryId: 'campus',
    skillTitle: 'Campus Errands & Delivery',
    expertiseTags: ['LAUNDRY', 'PICKUP', 'DELIVERY'],
    serviceIds: ['campus-1', 'campus-3'],
    averageRating: 4.9,
    reviewCount: 203,
  },
  {
    username: 'alexkwrites',
    displayName: 'Alex K.',
    handle: '@alexkwrites',
    avatarUrl: avatar('alexkwrites'),
    categoryId: 'career',
    skillTitle: 'Academic & Career Writing Editor',
    expertiseTags: ['RESUMES', 'APA STYLE', 'ESSAYS'],
    serviceIds: ['career-1', 'career-3'],
    averageRating: 4.6,
    reviewCount: 37,
  },
  {
    username: 'taylorw',
    displayName: 'Taylor W.',
    handle: '@taylorw',
    avatarUrl: avatar('taylorw'),
    categoryId: 'design',
    skillTitle: 'Campus Content & Video Creator',
    expertiseTags: ['POSTERS', 'FLYERS', 'BRANDING'],
    serviceIds: ['design-1', 'design-3'],
    averageRating: 4.5,
    reviewCount: 28,
  },
  {
    username: 'sarahm',
    displayName: 'Sarah M.',
    handle: '@sarahm',
    avatarUrl: avatar('sarahm'),
    categoryId: 'career',
    skillTitle: 'Startup Product & Pitch Coach',
    expertiseTags: ['INTERVIEWS', 'MOCK SESSIONS', 'LINKEDIN'],
    serviceIds: ['career-2', 'career-3'],
    averageRating: 4.8,
    reviewCount: 19,
  },
];

