"""Add embedding to user

Revision ID: f6791b74a8a3
Revises: fcf0ce585c90
Create Date: 2026-03-14 12:47:13.807934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6791b74a8a3'
down_revision: Union[str, Sequence[str], None] = 'fcf0ce585c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'embedding')
    # ### end Alembic commands ###
