"""Add subcategory filters model

Revision ID: facabe96e5ef
Revises: 9e8b8d663df2
Create Date: 2026-04-07 17:33:49.943961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'facabe96e5ef'
down_revision: Union[str, Sequence[str], None] = '9e8b8d663df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategory_filters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=False),
    sa.Column('filter_label', sa.String(), nullable=False),
    sa.Column('filter_type', sa.String(), nullable=False),
    sa.Column('filter_options', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategory_filters_subcategory'), 'subcategory_filters', ['subcategory'], unique=False)
    op.add_column('listings', sa.Column('subcategory', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('media_url', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('level', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('department', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('listings', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('review_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_listings_subcategory'), 'listings', ['subcategory'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_subcategory'), table_name='listings')
    op.drop_column('listings', 'review_count')
    op.drop_column('listings', 'average_rating')
    op.drop_column('listings', 'tags')
    op.drop_column('listings', 'department')
    op.drop_column('listings', 'level')
    op.drop_column('listings', 'media_url')
    op.drop_column('listings', 'subcategory')
    op.drop_index(op.f('ix_subcategory_filters_subcategory'), table_name='subcategory_filters')
    op.drop_table('subcategory_filters')
    # ### end Alembic commands ###
